CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "DayStates" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Color" text NOT NULL,
    CONSTRAINT "PK_DayStates" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GoalTemplates" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "UserId" uuid,
    CONSTRAINT "PK_GoalTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GoalTemplates_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "Token" text NOT NULL,
    "Expires" timestamp with time zone NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DayStateGoalTemplate" (
    "StatesId" uuid NOT NULL,
    "TemplatesId" uuid NOT NULL,
    CONSTRAINT "PK_DayStateGoalTemplate" PRIMARY KEY ("StatesId", "TemplatesId"),
    CONSTRAINT "FK_DayStateGoalTemplate_DayStates_StatesId" FOREIGN KEY ("StatesId") REFERENCES "DayStates" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DayStateGoalTemplate_GoalTemplates_TemplatesId" FOREIGN KEY ("TemplatesId") REFERENCES "GoalTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GoalItems" (
    "Id" uuid NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(256),
    "DaysNumber" integer NOT NULL,
    "DateStart" date NOT NULL,
    "UserId" uuid NOT NULL,
    "TemplateId" uuid NOT NULL,
    CONSTRAINT "PK_GoalItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GoalItems_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GoalItems_GoalTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "GoalTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GoalDates" (
    "Id" uuid NOT NULL,
    "Date" date NOT NULL,
    "Comment" character varying(1024),
    "StateId" uuid NOT NULL,
    "GoalId" uuid NOT NULL,
    CONSTRAINT "PK_GoalDates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GoalDates_DayStates_StateId" FOREIGN KEY ("StateId") REFERENCES "DayStates" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GoalDates_GoalItems_GoalId" FOREIGN KEY ("GoalId") REFERENCES "GoalItems" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_DayStateGoalTemplate_TemplatesId" ON "DayStateGoalTemplate" ("TemplatesId");

CREATE UNIQUE INDEX "IX_GoalDates_GoalId_Date" ON "GoalDates" ("GoalId", "Date");

CREATE INDEX "IX_GoalDates_StateId" ON "GoalDates" ("StateId");

CREATE INDEX "IX_GoalItems_TemplateId" ON "GoalItems" ("TemplateId");

CREATE INDEX "IX_GoalItems_UserId" ON "GoalItems" ("UserId");

CREATE UNIQUE INDEX "IX_GoalTemplates_Name" ON "GoalTemplates" ("Name");

CREATE INDEX "IX_GoalTemplates_UserId" ON "GoalTemplates" ("UserId");

CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240817095620_init', '8.0.8');

COMMIT;

